#!/usr/bin/python -u
#
# CS3700, Spring 2015
# Project 2 Starter Code
#

import sys
import socket
import time
import datetime
import select
import json

MSG_SIZE = 1500
DATA_SIZE = 1000
TIMEOUT = 0
SEQUENCE = 0

# Bind to localhost and an ephemeral port
IP_PORT = sys.argv[1]
UDP_IP = IP_PORT[0:IP_PORT.find(":")]
UDP_PORT = int(IP_PORT[IP_PORT.find(":")+1:])
dest = (UDP_IP, UDP_PORT)

# Set up the socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM) 
sock.settimeout(TIMEOUT)

# Our variables
send_window = 1
t = time.time()
sent_packets = {}
rtt_estimate = 0
RTO = 2

def log(string):
  sys.stderr.write(datetime.datetime.now().strftime("%H:%M:%S.%f") + " " + string + "\n")

def send_next_packet(retransmit=False, ret_seq=0):
  global SEQUENCE
  if not retransmit:
    data = sys.stdin.read(DATA_SIZE)
  if retransmit or (len(data) > 0):
    # Add data we're sending to unacked data
    if retransmit:
      log("ATTEMPTING RETRANSMISSION")
      msg = sent_packets[ret_seq][0]
    else:
      msg = {"sequence": SEQUENCE, "data": data, "ack": False, "eof": False}
    
    msg_string = json.dumps(msg)
    if sock.sendto(msg_string, dest) < len(msg_string):
      log("[error] unable to fully send packet")
    else:
      if retransmit:
        sent_packets[ret_seq] = (msg, time.time(), False)
      else:
        SEQUENCE += len(data)
        sent_packets[SEQUENCE] = (msg, time.time(), True)
      
      log("[send data] " + str(msg['sequence']) + " (" + str(len(msg['data'])) + ")")
    return True
  else:
    return False

# Send first packet
send_next_packet()

def rtt_sample(out_time, ack_time):
  global RTO, rtt_estimate
  alpha = 0.8
  beta = 1.15
  if rtt_estimate == 0:
    rtt_estimate = ack_time-out_time
  else:
    rtt_estimate = rtt_estimate*alpha + (ack_time-out_time)*(1-alpha)
  RTO = rtt_estimate*beta

# Now read in data, send packets
while True:
  try:
    if len(sent_packets) < send_window:
        # Try to send next packet; break if no more data
        if (not send_next_packet()) and len(sent_packets) == 0:
          break
          
    result = sock.recvfrom(MSG_SIZE)
    # if we receive anything, continue
    if result:
      log("RECEIVED PACKET")
      (data, addr) = result
      try:
        decoded = json.loads(data)
        
        # Match our window to advertised window from receiver
        if decoded['window']:
          send_window = decoded['window']
          
        # Look at the ack received and process it
        if decoded['ack'] in sent_packets.keys():
          # delete the packet from sent_packets
          if sent_packets[decoded['ack']][2]:
            rtt_sample(sent_packets[decoded['ack']][1], time.time())
          del sent_packets[decoded['ack']]
          log("[recv ack] " + str(SEQUENCE))

      except (ValueError, KeyError, TypeError) as e:
        log(str(e))
        log("[recv corrupt packet]")
    else:
      log("[error] timeout")
      sys.exit(-1)
  except:
      # Retransmission logic
      for seq in sent_packets.keys():
        msg = sent_packets[seq][0]
        to = sent_packets[seq][1]
        if time.time() - to > RTO:
          log("REACHED TIMEOUT")
          # didn't receive ack within time frame, retransmit
          t = time.time()
          if (not send_next_packet(retransmit=True, ret_seq=seq)):
            break

sock.sendto(json.dumps({"eof": True, "data": "", "sequence": SEQUENCE, "ack": False}), dest)
sys.exit(0)
