#!/usr/bin/perl

my @tests = split('\n', `grep -h '' /course/cs3700f17/stats/project3/* 2>/dev/null | cut -f1 | sort | uniq`);

if ($#tests == -1) {
  print "No test submissions available yet.\n";
}

foreach $t (@tests) { 
  print "----- TEST: $t -----\n";
  print "Quickest:\n";
  my @res = split('\n', `grep -h '' /course/cs3700f17/stats/project3/* | grep '$t' | sort -t"\t" -k3n | cut -f2,3`);
  my %done = ();
  my $i = 1;
  foreach $r (@res) {
    if ($r =~ m|^([^\t]*)\t([^\r\t\n]*)|) {
      if (! exists $done{$1}) {
        print "$i: $1\t" . sprintf("%.3f", $2/1000) . " sec\n";
        $done{$1} = 1;
        $i++;
      }
    }
  }

  print "\nMost Efficient:\n";
  my @res = split('\n', `grep -h '' /course/cs3700f17/stats/project3/* | grep '$t' | sort -t"\t" -k4n | cut -f2,4 `);
  my %done = ();
  my $i = 1;
  foreach $r (@res) {
    if ($r =~ m|^([^\t]*)\t([^\r\t\n]*)|) {
      if (! exists $done{$1}) {
        print "$i: $1\t" . format_bytes($2) . "B sent\n";
        $done{$1} = 1;
        $i++;
      }
    }
  }
  print "\n";
}

sub format_bytes {
  my ($a) = @_;

  if ($a < 1024) { return $a; }
  if ($a < 1024 * 1024) { return int($a/1024) . "K"; }
  if ($a < 1024 * 1024 * 1024) { return int($a/(1024*1024)) . "M"; }
  if ($a < 1024 * 1024 * 1024 * 1024) { return int($a/(1024*1024*1024)) . "G"; }
}

#  my @res = split('\n', `grep -h '' /course/cs3700f13/stats/project3/* | grep '$t' | sort -t"\t" -k3n | cut -f2,3 | grep -n ''`);
#  foreach $r (@res) {
#    if ($r =~ m|^([^\t]*)\t([^\r\t\n]*)|) {
#      print "$1\t" . sprintf("%.3f", $2/1000) . " sec\n";
#    }
#  }
