#!/usr/bin/python -u
# The -u makes output unbuffered, so it will show up immediately
import sys
import socket
import select
import json
import time


# Pads the name with null bytes at the end
def pad(name):
	result = '\0' + name
	while len(result) < 108:
		result += '\0'
	return result

# GET PORT ID FOR A PORT
def port_id(port):
	return sockets.index(port)

# Create a JSON string representation of a packet
def packet(source, dest, form, message):
	packet = {'source': source, 'dest': dest, 'type':form, 'message':message}
	return packet

# RETURN PORT ID A PACKET WAS SENT ON
def get_sent_port(packet):
	s = packet['source']
	return s[s.find('/')+1:]
	
# Send a BPDU packet
def send_bpdu():
	global t
	message = {'id': id, 'root': root, 'cost': cost}
	# Calls select with all the sockets; change the timeout value (1)
	for x in sockets:
		port_num = port_id(x)
		# Create and send the BPDU JSON packet
		p = packet(id + "/" + str(port_num), 'ffff', 'bpdu', message)
		if port_num not in BPDUs:
			BPDUs[port_num] = (p, time.time())
		else:
			better = comp_bpdu(BPDUs[port_num][0], p)
			if better:
				temp = better.copy()
				BPDUs[port_num] = (temp, time.time())
		x.sendall(str(json.dumps(p)))
	t = time.time()


# Send a message to all sockets
def send_message(ports_to_send, message):
	# Calls select with all the sockets; change the timeout value (1)
	for x in ports_to_send:
		x.sendall(message)


# Determine the type of a packet and read the data
def read_packet(data, port):
	global buffer
	data = json.loads(data)
	if data['type'] == 'bpdu':
		# The packet is a BPDU packet
		return read_bpdu(data['message'], data, port)
	elif data['type'] == 'data':
		# The packet is of some other type
		if tree_comp:
			return process_data(data, port)
		else:
			buffer.append((data, port))


# Process a non-BPDU packet
def process_data(data, port):
	global forwarding_table
	if port in designated_ports or port == root_port:
		print "Received message " + str(data['message']['id']) + " on port " + str(port_id(port)) + " from " + data['source'] + " to " + data['dest']
		if data['source'] not in forwarding_table:
			# Create a forwarding table entry for the source of the packet if one does not already exist
			forwarding_table[data['source']] = (port, time.time())
		if data['dest'] in forwarding_table:
			if forwarding_table[data['dest']][0] == port:
				forwarding_table[data['dest']] = (port, time.time())
			# If the destination of the packet is in the forwarding table, send to proper port
			print "Forwarding message " + str(data['message']['id']) + " to port " + str(port_id(port))
			send_to = [forwarding_table[data['dest']][0]]
			# Verify we are not sending to the port that the packet came from
			if port not in send_to:
				send_message(send_to, str(json.dumps(data)))
			else:
				print "Not forwarding message " + str(data['message']['id']) + " to port " + str(port_id(port))
		else:
			# If the destination of the packet is NOT in the forwarding table, send to designated ports and root port
			ports_to_send = list(designated_ports) + [root_port] if root_port is not None else list(designated_ports)
			# Verify we are not sending to the port that the packet came from
			if port in ports_to_send:
				ports_to_send.remove(port)
			print "Broadcasting message " + str(data['message']['id']) + " to all ports"
			send_message(ports_to_send, str(json.dumps(data)))

def clear_table(port):
	for key in forwarding_table.keys():
		if forwarding_table[key][0] == port:
			del forwarding_table[key]
			
# Designate given port
def designate_port(port):
	global designated_ports, forwarding_table
	if port not in designated_ports and port != root_port:
		designated_ports.append(port)
		print("Designated port: " + id + "/" + str(port_id(port)))
		# Flush the forwarding table
		clear_table(port)


# Disable given port		
def disable_port(port):
	global designated_ports
	if port in designated_ports:
		designated_ports.remove(port)
		print("Disabled port: " + id + "/" + str(port_id(port)))
		# Flush the forwarding table
		clear_table(port)

# Changes the root for this bridge, with option to change root id, cost or both along with the port
def change_root(port, new_root, new_cost):
	global root_port, root, cost
	if new_root:
		root = new_root
		print "New root: " + id + "/" + root
	if new_cost:
		cost = new_cost
	old_port = root_port
	root_port = port
	# Un-designate the root port
	disable_port(port)
	if old_port is not None:
		designate_port(old_port)
		clear_table(old_port)
	print "Root port: " + id + "/" + str(port_id(port))
	clear_table(port)
	send_bpdu()

# Compare two BPDUs, return the second if it's better, otherwise return None
def comp_bpdu(packet1, packet2):
	data1 = packet1['message']
	data2 = packet2['message']
	
	# Found one with a smaller root id
	if int(data2['root'], 16) < int(data1['root'], 16):
		return packet2
	# Equal root IDs
	if int(data2['root'], 16) == int(data1['root'], 16):
		if packet1['source'] == packet2['source']:
			return packet2
		if data2['cost'] < data1['cost']:
			return packet2
		if data2['cost'] == data1['cost'] and int(packet2['source'].split("/")[0], 16) <= int(packet1['source'].split("/")[0], 16):
			return packet2
	return None
	
# Read the BPDU packet and take neccesary actions
def read_bpdu(data, packet, port):
	global cost, root, root_port, designated_ports, forwarding_table, BPDUs
	port_num = port_id(port)

	# Deals with BPDU comparisons
	if port_num in BPDUs:
		better = comp_bpdu(BPDUs[port_num][0], packet)
		if better:
			temp = better.copy()
			BPDUs[port_num] = (better, time.time())
		else:
			BPDUs[port_num] = (BPDUs[port_num][0], time.time())
	# If for some reason there's nothing in BPDUs for this
	else:
		temp = packet.copy()
		BPDUs[port_num] = (temp, time.time())
	
	handle_bpdu(BPDUs[port_num][0], port)


# Processes a BPDU once the best one for a port has been decided upon
def handle_bpdu(packet, port):
	data = packet['message']
	
	# found a root with lower ID
	if int(data['root'], 16) < int(root, 16):
		change_root(port, data['root'], data['cost']+1)		
	# bpdu agrees on root id
	elif int(data['root'], 16) == int(root, 16):
		# using this port would give us a lower cost
		if data['cost'] + 1 < cost:
			change_root(port, None, data['cost']+1)
		# other BPDU gives a better path to root for hosts on the LAN
		elif data['cost'] < cost:
			disable_port(port)
		# this bridge provides a better path to root for hosts on the LAN
		elif data['cost'] > cost:
			designate_port(port)
		# other BPDU has equal cost to ours
		elif data['cost'] == cost:
			# their bridge ID is lower, they should be the designated bridge for the LAN
			if int(data['id'], 16) < int(id, 16):
				disable_port(port)
			# our bridge ID is lower, we should be designated bridge for the LAN
			elif int(data['id'], 16) > int(id, 16):
				designate_port(port)
			# BPDU came from us, fix it
			else:
				sent_port = int(get_sent_port(packet))
				received_port = int(port_id(port))
				# sent out on lower port id, disable receiver
				if sent_port < received_port and sockets[received_port] in designated_ports:
					disable_port(port)
				# received on lower port id, disable sender
				elif sent_port > received_port and port in designated_ports:
					disable_port(sockets[sent_port])
				elif sent_port == received_port:
					designate_port(port)

# Handle timeouts for forwarding table and BPDUs, also checks whether the tree is complete
def timeouts():
	global forwarding_table, BPDUs, cost, root, root_port, designated_ports, tree_comp
	# Timeout forwarding table entries after five seconds
	if len(forwarding_table) > 0:
		for key in forwarding_table.keys():
			if time.time() - forwarding_table[key][1] > 5:
				del forwarding_table[key]
				
	# Timeout BPDUs if not refreshed after .750 seconds
	stat = True
	if len(BPDUs) > 0:
		for key in BPDUs.keys():
			# monitors tree completion based on if all have the same root
			stat = stat and (int(BPDUs[key][0]['message']['root'], 16) == int(root, 16))
			if time.time() - BPDUs[key][1] > 0.75:
				cost = 0
				root = id
				root_port = None
				forwarding_table = dict()
				BPDUs = dict()
				designated_ports = list(sockets)
				send_bpdu()
	tree_comp = stat

if __name__ == "__main__":
	# Global variables ---
	# ID of this bridge
	id = sys.argv[1]
	# IDs of rest of LAN
	LAN = sys.argv[2:]
	# List of sockets
	sockets = []
	# ID of root node for this bridge (Defaults to this bridge)
	root = id
	# Number of leaps to root (Defaults to zero)
	cost = 0
	# Port that connects to the current root node (Defaults to this bridge, None)
	root_port = None
	# List representing the bridge forwarding table
	forwarding_table = dict()
	# Best BPDU for a given port
	BPDUs = dict()
	buffer = list()
	tree_comp = False
	
	# Creates sockets and connects to them
	for x in range(len(LAN)):
		s = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
		s.connect(pad(LAN[x]))
		sockets.append(s)

	# List of designated ports
	designated_ports = list(sockets)
	print "Bridge " + id + " starting up"

	# Current time, serves to start a timer
	send_bpdu()
	t = time.time()
	# Main loop
	while True:
		timeouts()
		if tree_comp and len(buffer) > 0:
			buffer.reverse()
			for item in buffer:
				process_data(item[0], item[1])
	
		# Calls select with designated sockets; change the timeout value (1)
		ready, ignore, ignore2 = select.select(sockets, [], [], 0.25)
		# Reads from each of the ready sockets
		for x in ready:
			data = x.recv(1500)
			read_packet(data, x)
		
		# If 500ms has passed, send out BPDUs
		if (time.time() - t) > 0.5:
			send_bpdu()
			# Reset the timer
			t = time.time()

